var products=[
{id:'ST1699108',
name:"Study Table with Two Drawer in Nut Brown Finish by Mikareo",
price:7499,
oldPrice:'Rs. 13496',
image:'items/500.jpg',
video:'https://youtu.be/1jDkrhxWLUA',
category:'Table',
material:'Engineered Wood',
date:'22 June 2019',
about:'Mikareo is a classic amalgamation of form and function. Crafted for compact homes, the range is clean and convenient and has an understated design aesthetic that adapts to any space. Modern is a distinct, defined style which originated in the early 1800s.'},

{id:'ST1699108',
name:"Product Number 2",
price:7000,
oldPrice:'Rs. 13496',
image:'items/500.jpg',
video:'https://youtu.be/1jDkrhxWLUA',
category:'Sofa',
material:'Plywood',
date:'06 June 2019',
about:'Mikareo is a classic amalgamation of form and function. Crafted for compact homes, the range is clean and convenient and has an understated design aesthetic that adapts to any space. Modern is a distinct, defined style which originated in the early 1800s.'},

{id:'ST1699108',
name:"Product Number 3",
price:1200,
oldPrice:'Rs. 13496',
image:'items/500.jpg',
video:'https://youtu.be/1jDkrhxWLUA',
category:'Door',
material:'Plastic',
date:'02 June 2020',
about:'Mikareo is a classic amalgamation of form and function. Crafted for compact homes, the range is clean and convenient and has an understated design aesthetic that adapts to any space. Modern is a distinct, defined style which originated in the early 1800s.'},

{id:'ST1699108',
name:"Product Number 4",
price:5000,
oldPrice:'Rs. 13496',
image:'items/500.jpg',
video:'https://youtu.be/1jDkrhxWLUA',
category:'Table',
material:'Glass',
date:'20 May 2019',
about:'Mikareo is a classic amalgamation of form and function. Crafted for compact homes, the range is clean and convenient and has an understated design aesthetic that adapts to any space. Modern is a distinct, defined style which originated in the early 1800s.'},

{id:'ST1699108',
name:"Product Number 5",
price:1000,
oldPrice:'Rs. 13496',
image:'items/500.jpg',
video:'https://youtu.be/1jDkrhxWLUA',
category:'Door',
material:'Glass',
date:'22 June 2016',
about:'Mikareo is a classic amalgamation of form and function. Crafted for compact homes, the range is clean and convenient and has an understated design aesthetic that adapts to any space. Modern is a distinct, defined style which originated in the early 1800s.'},

{id:'ST1699108',
name:"Product Number 6",
price:9900,
oldPrice:'Rs. 13496',
image:'items/500.jpg',
video:'https://youtu.be/1jDkrhxWLUA',
category:'Table',
material:'Plywood',
date:'05 June 2020',
about:'Mikareo is a classic amalgamation of form and function. Crafted for compact homes, the range is clean and convenient and has an understated design aesthetic that adapts to any space. Modern is a distinct, defined style which originated in the early 1800s.'},


]