var products=[
{id:'FRNTR2201',
name:"Elegantly Designed Drawer Chest",
price:5000,
oldPrice:'Rs. 7000',
image:'items/FRNTR2201.jpg',
video:'https://youtu.be/1jDkrhxWLUA',
category:'Drawer',
material:'Plywood',
date:'22 June 2019',
about:'Mikareo is a classic amalgamation of form and function. Crafted for compact homes, the range is clean and convenient and has an understated design aesthetic that adapts to any space. Modern is a distinct, defined style which originated in the early 1800s.'},

{id:'FRNTR2202',
name:"Black Sofa set with Stylish Chairs",
price:7000,
oldPrice:'Rs. 9000',
image:'items/FRNTR2202.jpg',
video:'https://youtu.be/1jDkrhxWLUA',
category:'Sofa',
material:'Wood',
date:'06 June 2019',
about:'Mikareo is a classic amalgamation of form and function. Crafted for compact homes, the range is clean and convenient and has an understated design aesthetic that adapts to any space. Modern is a distinct, defined style which originated in the early 1800s.'},

{id:'FRNTR2203',
name:"Modern and Stylish Complete Kitchen Furniture set",
price:1500,
oldPrice:'Rs. 17499',
image:'items/FRNTR2203.jpg',
video:'https://youtu.be/1jDkrhxWLUA',
category:'Kitchen',
material:'Plywood',
date:'02 June 2020',
about:'Mikareo is a classic amalgamation of form and function. Crafted for compact homes, the range is clean and convenient and has an understated design aesthetic that adapts to any space. Modern is a distinct, defined style which originated in the early 1800s.'},

{id:'FRNTR2204',
name:"Product Number 4",
price:5000,
oldPrice:'Rs. 13496',
image:'items/FRNTR2204.jpg',
video:'https://youtu.be/1jDkrhxWLUA',
category:'Table',
material:'Glass',
date:'20 May 2019',
about:'Mikareo is a classic amalgamation of form and function. Crafted for compact homes, the range is clean and convenient and has an understated design aesthetic that adapts to any space. Modern is a distinct, defined style which originated in the early 1800s.'},

{id:'FRNTR2205',
name:"Product Number 5",
price:1000,
oldPrice:'Rs. 13496',
image:'items/FRNTR2205.jpg',
video:'https://youtu.be/1jDkrhxWLUA',
category:'Door',
material:'Glass',
date:'22 June 2016',
about:'Mikareo is a classic amalgamation of form and function. Crafted for compact homes, the range is clean and convenient and has an understated design aesthetic that adapts to any space. Modern is a distinct, defined style which originated in the early 1800s.'},

{id:'FRNTR2206',
name:"Product Number 6",
price:9900,
oldPrice:'Rs. 13496',
image:'items/FRNTR2206.jpg',
video:'https://youtu.be/1jDkrhxWLUA',
category:'Table',
material:'Plywood',
date:'05 June 2020',
about:'Mikareo is a classic amalgamation of form and function. Crafted for compact homes, the range is clean and convenient and has an understated design aesthetic that adapts to any space. Modern is a distinct, defined style which originated in the early 1800s.'},

{id:'FRNTR2207',
name:"Product Number 6",
price:9900,
oldPrice:'Rs. 13496',
image:'items/FRNTR2207.jpg',
video:'https://youtu.be/1jDkrhxWLUA',
category:'Table',
material:'Plywood',
date:'05 June 2020',
about:'Mikareo is a classic amalgamation of form and function. Crafted for compact homes, the range is clean and convenient and has an understated design aesthetic that adapts to any space. Modern is a distinct, defined style which originated in the early 1800s.'},

{id:'FRNTR2208',
name:"Product Number 6",
price:9900,
oldPrice:'Rs. 13496',
image:'items/FRNTR2208.jpg',
video:'https://youtu.be/1jDkrhxWLUA',
category:'Table',
material:'Plywood',
date:'05 June 2020',
about:'Mikareo is a classic amalgamation of form and function. Crafted for compact homes, the range is clean and convenient and has an understated design aesthetic that adapts to any space. Modern is a distinct, defined style which originated in the early 1800s.'},

{id:'FRNTR2209',
name:"Product Number 6",
price:9900,
oldPrice:'Rs. 13496',
image:'items/FRNTR2209.jpg',
video:'https://youtu.be/1jDkrhxWLUA',
category:'Table',
material:'Plywood',
date:'05 June 2020',
about:'Mikareo is a classic amalgamation of form and function. Crafted for compact homes, the range is clean and convenient and has an understated design aesthetic that adapts to any space. Modern is a distinct, defined style which originated in the early 1800s.'},

{id:'FRNTR2210',
name:"Product Number 6",
price:9900,
oldPrice:'Rs. 13496',
image:'items/FRNTR2210.jpg',
video:'https://youtu.be/1jDkrhxWLUA',
category:'Table',
material:'Plywood',
date:'05 June 2020',
about:'Mikareo is a classic amalgamation of form and function. Crafted for compact homes, the range is clean and convenient and has an understated design aesthetic that adapts to any space. Modern is a distinct, defined style which originated in the early 1800s.'},


]